# Generated by Django 3.2.3 on 2021-05-28 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gernes', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=50)),
                ('storyline', models.TextField(default='')),
                ('stars', models.CharField(max_length=255)),
                ('creators', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('run_time', models.IntegerField(help_text='Enter run length in minutes')),
                ('trailer', embed_video.fields.EmbedVideoField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='media')),
                ('production_companies', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.auditorium')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.auditorium')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.customer')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.seat')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.showtime')),
            ],
            options={
                'unique_together': {('time', 'customer', 'seat')},
            },
        ),
    ]
